// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function NewDocument() {
  return window['go']['main']['App']['NewDocument']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenMarkdownFile() {
  return window['go']['main']['App']['OpenMarkdownFile']();
}

export function ReadFileAsDataURL(arg1) {
  return window['go']['main']['App']['ReadFileAsDataURL'](arg1);
}

export function SaveMarkdownFile(arg1) {
  return window['go']['main']['App']['SaveMarkdownFile'](arg1);
}

export function SaveMarkdownFileAs(arg1) {
  return window['go']['main']['App']['SaveMarkdownFileAs'](arg1);
}
