// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStartupFile():Promise<main.DocumentPayload>;

export function NewDocument():Promise<main.DocumentPayload>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenMarkdownFile():Promise<main.DocumentPayload>;

export function ReadFileAsDataURL(arg1:string):Promise<string>;

export function SaveMarkdownFile(arg1:string):Promise<main.DocumentPayload>;

export function SaveMarkdownFileAs(arg1:string):Promise<main.DocumentPayload>;
